# -*- coding: utf-8 -*-
"""ElasticNet_第二次

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fDZAZxQxLRDV1XPCc4LNewoxvp158Z-f
"""

import numpy as np
import pandas as pd 
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

train=pd.read_csv("/content/drive/MyDrive/Toehold_Switch_Training_Library_v1.csv")
del train['Toehold switch number']
y = train.pop('ON/OFF')
X = train

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2)


EN = ElasticNet()

EN.fit(X_train,y_train)


pred=EN.predict(X_test)

r2_score(y_test, pred)