# -*- coding: utf-8 -*-
"""Kernel Ridge Regression_第三次

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13S2EDq-1JPUvq7f0j7bFPn4JVPlE4w4u
"""

import numpy as np
import pandas as pd 
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

train=pd.read_csv("/content/drive/MyDrive/Toehold_Switch_Training_Library_v1.csv")
del train['Toehold switch number']
y = train.pop('ON/OFF')
X = train

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2)


KR = KernelRidge(kernel='laplacian') #Valid values for metric are:[‘additive_chi2’, ‘chi2’, ‘linear’, ‘poly’, ‘polynomial’, ‘rbf’, ‘laplacian’, ‘sigmoid’, ‘cosine’]

KR.fit(X_train,y_train)

pred=KR.predict(X_test)

r2_score(y_test, pred)