# -*- coding: utf-8 -*-
"""SVR_第三次

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UQxZeKHXNY9G4YMt47slRvDMoUsW9z2X
"""

import numpy as np
import pandas as pd 
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

train=pd.read_csv("/content/drive/MyDrive/toehold library_v3.csv")
del train['Toehold switch number']
y = train.pop('ON/OFF')
X = train

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2)

SVR = SVR()

SVR.fit(X_train,y_train)


pred=SVR.predict(X_test)

r2_score(y_test, pred)